### ISSUE TITLE
Extension's CSS interferes with CSS of the loaded page and vice versa.

### ISSUE THREAD

**Issue by hitgoeb** [ProSvizraRumantscha/pledarix#4]
E.g. https://www.washingtonpost.com 
![wp](https://user-images.githubusercontent.com/27008049/53700871-2ea08900-3df7-11e9-80ee-f2cd7e872c62.jpg)

**Comment by hitgoeb** [comment]
Also pledarigrond.ch

**Comment by gion-andri** [comment]
Fixed in 18c703ee8ea45ec4315b08277936098768aa9bcd
